name: build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt

      - run: mvn --batch-mode verify
